-- DB CALENDAR
CREATE DATABASE DB_CALENDAR;
USE DB_CALENDAR;


-- USER MEMBER
CREATE TABLE USER_MEMBER(
	NO 				INT AUTO_INCREMENT,
    ID 				VARCHAR(20) NOT NULL,
    PW 				VARCHAR(100) NOT NULL,
    MAIL 			VARCHAR(50) NOT NULL,
    PHONE 			VARCHAR(50) NOT NULL,
    AUTHORITY_NO 	INT DEFAULT 1,
    REG_DATE		TIMESTAMP DEFAULT NOW(),
    MOD_DATE		TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY(NO),
    FOREIGN KEY(AUTHORITY_NO) REFERENCES USER_AUTHORITY(NO)
);
ALTER TABLE USER_MEMBER ADD UNIQUE(ID);
SELECT * FROM USER_MEMBER;
DESC USER_MEMBER;
DROP TABLE USER_MEMBER;

-- USER_AUTHORITY(권한)
CREATE TABLE USER_AUTHORITY(
	NO	INT AUTO_INCREMENT,
    ROLE_NAME	VARCHAR(20) NOT NULL,
    PRIMARY KEY(NO)
);

INSERT INTO USER_AUTHORITY(ROLE_NAME) VALUES('PRE_USER');
INSERT INTO USER_AUTHORITY(ROLE_NAME) VALUES('USER');

SELECT * FROM USER_AUTHORITY;

SELECT * FROM USER_MEMBER M
JOIN USER_AUTHORITY A
ON M.AUTHORITY_NO = A.NO;

DROP TABLE USER_MEMBER;
DROP TABLE USER_AUTHORITY;

SHOW TABLES;
DESC USER_MEMBER;
DESC USER_AUTHORITY;
SELECT * FROM USER_MEMBER;
SELECT * FROM USER_AUTHORITY;


DESC ADMIN_MEMBER;
DESC ADMIN_AUTHORITY;
SELECT * FROM ADMIN_MEMBER;
SELECT * FROM ADMIN_AUTHORITY;

INSERT INTO ADMIN_AUTHORITY (no, auth_role_name) VALUES (1, 'ROLE_USER');
INSERT INTO ADMIN_AUTHORITY (no, auth_role_name) VALUES (2, 'ROLE_ADMIN');
INSERT INTO ADMIN_AUTHORITY (no, auth_role_name) VALUES (3, 'SUPER_ADMIN');



SELECT * FROM PLAN;
